export class BYT_QUOTES {
	
	listOfQuotes(){
		let byt_quotes = [
			"\"Beware of little expenses. A small leak will sink a great ship\"",
			"\"A budget tells us what we can't afford, but it doesn't stop us from buying it\"",
			"\"About the time we can make the ends meet, somebody moves the ends\"",
			"\"Know where you stand financially\"",
			"\"As sure as the spring will follow the winter, prosperity and economic growth will follow recession\"",
			"\"Save cash during the good times, invest cash during the bad times\"",
			"\"The more stable your emotions, the easier it is to save\"",
			"\"Unstable emotions usually lead to high credit card\"",
			"\"Financial freedom is available to those who learn about it and work for it\"",
			"\"Building wealth is usually repetitive and boring\"",
			"\"Because of divorce and life expectancy, it's important for women to control thier finances\"",
			"\"When money realizes that it is in good hands, it wants to stay and multiply in those hands\"",
			"\"Every time you borrow money, you're robbing your future self\"",
			"\"Success is fueled by being persistent and consistent\"",
			"\"When it comes to money, ignorance is NOT bliss. What you don't know CAN hurt you\"",
			"\"I used to say why save money if I'll die tomorrow, I haven’t died yet and I have nothing to survive on\"",
			"\"You don’t have to be a miser, just be wiser with your money\"",
			"\"You got loans to pay off, and I got deposits to make\"",
			"\"We are very much aware of the existence of money, but not so much the concept of currency\"",
			"\"An investment in knowledge pays the best interest\"",
			"\"I will tell you how to become rich. Close the doors. Be fearful when others are greedy. Be greedy when others are fearful\"",
			"\"Invest in yourself. Your career is the engine of your wealth\"",
			"\"Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas\"",
			"\"Budgeting has only one rule: Do not go over budget\"",
			"\"If repairing one's credit is as easy as sending some dispute letters to the credit bureaus then why doesn't everyone have good credit?\"",
			"\"A bank is a place that will lend you money if you can prove that you don’t need it\"",
			"\"We make ourselves rich by making our wants few\"",
			"\"Being frugal does not mean being cheap! It means being economical and avoiding waste\"",
			"\"It is great wealth to a soul to live frugally with a contented mind\"",
			"\"If you can, you will quickly find that the greatest rate of return you will earn is on your own personal spending. Being a smart shopper is the first step to getting rich\"",
			"\"Save a part of your income and begin now, for the man with a surplus controls circumstances and the man without a surplus is controlled by circumstances\"",
			"\"If saving money is wrong, I don't want to be right\"",
			"\"A simple fact that is hard to learn is that the time to save money is when you have some\"",
			"\"He or she who does not economize will have to agonize\"",
			"\"The best way to save money is not to lose it\"",
			"\"A women's best protection is money of her own\"",
			"\"Don't count your check-ins before they cash\"",
			"\"It's not your salary that makes you rich, it's your spending habits\"",
			"\"This first wealth is health\"",
			"\"Wealth is the slave of a wise man. The master of a fool\"",
			"\"Wealth is the product of a man or woman's capacity to think\"",
		];
		return byt_quotes;
	}
}